services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: