basePath: /
host: localhost:8090
info:
  contact:
    email: epishcom@gmail.com
    name: George Epishev
  description: Music Info is a service for searching and adding music to your library.
  title: Music Info
  version: 0.0.1
paths: {}
swagger: "2.0"
